In [2]:
def match_words(words):
  ctr = 0

  for word in words:
    if len(word) > 1 and word[0] == word[-1]:
      ctr += 1
  return ctr

print(match_words(['abc', 'xyz', 'aba', '1221']))

2


In [4]:
def match_words(words):
  ctr = []

  for word in words:
    if len(word) > 1 and word[0] == word[-1]:
      ctr.append(word)
  return ctr

print(match_words(['abc', 'xyz', 'aba', '1221']))

['aba', '1221']


# Enumerate


enumerate() function allows you to create an index for each item in the object you give it. You can use list comprehension, or even unpack the enumerate object directly into a list, to write a nice simple one-liner.


In [3]:
names = ['Jerry', 'Kramer', 'Elaine', 'George', 'Newman']

In [ ]:
indexed_names = []
for i in range(len(names)):
    index_name = (i, names[i])
    indexed_names.append(index_name)

In [2]:
# Rewrite the for loop to use enumerate
indexed_names = []
for i,name in enumerate(names):
    index_name = (i,name)
    indexed_names.append(index_name) 
print(indexed_names)

# Rewrite the above for loop using list comprehension
indexed_names_comp = [(i,name) for i,name in enumerate(names)]
print(indexed_names_comp)

# Unpack an enumerate object with a starting index of one
# Create another list (indexed_names_unpack) by using the star character (*) 
# to unpack the enumerate object created from using enumerate() on names. 
# This time, start the index for enumerate() at one instead of zero.

indexed_names_unpack = [*enumerate(names, 1)]
print(indexed_names_unpack)

[(0, 'Jerry'), (1, 'Kramer'), (2, 'Elaine'), (3, 'George'), (4, 'Newman')]
[(0, 'Jerry'), (1, 'Kramer'), (2, 'Elaine'), (3, 'George'), (4, 'Newman')]
[(1, 'Jerry'), (2, 'Kramer'), (3, 'Elaine'), (4, 'George'), (5, 'Newman')]


# MAP function

In [13]:
# Use map to apply str.upper to each element in names
names_map  = map(str.upper, names )

# Print the type of the names_map
print(type(names_map))

<class 'map'>


In [11]:
# Unpack names_map into a list
names_uppercase = [*names_map]

# Print the list created above
print(names_uppercase)

['JERRY', 'KRAMER', 'ELAINE', 'GEORGE', 'NEWMAN']


In [14]:
na=list(names_map)
print(na)

['JERRY', 'KRAMER', 'ELAINE', 'GEORGE', 'NEWMAN']


In [6]:
import numpy as np
# Create a list of arrival times
#Use range() to create a list of arrival times (10 through 50 incremented by 10).
# Create the list arrival_times by unpacking the range object.
arrival_times = [*range(10,60,10)]

arrival_times

[10, 20, 30, 40, 50]

In [8]:
# Convert arrival_times to an array and update the times
arrival_times_np = np.array(arrival_times) # COVERTING TO numpy for calculation

new_times = arrival_times_np - 3

print(arrival_times_np, new_times)

[10 20 30 40 50] [ 7 17 27 37 47]


In [9]:
# Use list comprehension and enumerate to pair guests to new times
guest_arrivals = [(names[i],time) for i,time in enumerate(new_times)]
guest_arrivals

[('Jerry', 7), ('Kramer', 17), ('Elaine', 27), ('George', 37), ('Newman', 47)]

# np.array

numpy arrays allows you to take advantage of an array's memory efficient nature and easily perform mathematical operations on your data.

In [32]:
import numpy as np

nums=np.array([[ 1, 2,  3 , 4,  5],
              [6 , 7 , 8 , 9 ,10]])

In [28]:
# Print second row of nums
print(nums[1,:])

[ 6  7  9  9 10]


In [29]:
# Print all elements of nums that are greater than six
print(nums[nums > 6])

[ 7  9  9 10]


In [30]:
# Double every element of nums
nums_dbl = nums * 2
print(nums_dbl)

[[ 2  4  8  8 10]
 [12 14 18 18 20]]


In [31]:
# Replace the third column of nums
nums[:,2] = nums[:,2] + 1
print(nums)

[[ 1  2  5  4  5]
 [ 6  7 10  9 10]]


In [13]:
import pandas as pd
s = pd.Series(list('abca'))

In [14]:
s

0    a
1    b
2    c
3    a
dtype: object

In [15]:
pd.get_dummies(s)

a  b  c
0  1  0  0
1  0  1  0
2  0  0  1
3  1  0  0

In [22]:
df = pd.DataFrame({'BADA': ['a', 'b', 'a'], 'MIDDLE_WALA': ['b', 'a', 'c'],
                   'CHOTA': [1, 2, 3]})
df

BADA MIDDLE_WALA  CHOTA
0    a           b      1
1    b           a      2
2    a           c      3

In [23]:
import pandas as pd
pd.get_dummies(df, prefix=['col1', 'col2']) # COLUMN BADA AND MIDDLE GOT CONVERTED TO DUMMY AS THER WERE CATAGORICAL

CHOTA  col1_a  col1_b  col2_a  col2_b  col2_c
0      1       1       0       0       1       0
1      2       0       1       1       0       0
2      3       1       0       0       0       1

In [21]:
pd.get_dummies(df,prefix=['col1', 'col2'], drop_first= True)#drop_first->True WILL ELIMATE THE DUMMY TRAP BY DELETING FIRST COLUMN

C  col1_b  col2_b  col2_c
0  1       0       1       0
1  2       1       0       0
2  3       0       0       1

In [24]:
pd.get_dummies(df,columns=['BADA', 'MIDDLE_WALA'], drop_first= True) # columns-> columns= will specify the target columns

CHOTA  BADA_b  MIDDLE_WALA_b  MIDDLE_WALA_c
0      1       0              1              0
1      2       1              0              0
2      3       0              0              1